groups:
- name: memory_alerts
  rules:
  - alert: HighMemoryUsage
    expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 40
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Memory Usage over 40%"
      description: "Memory Usage over 40%"
